// VSCode-style settings. Nova keeps a read-only Default Settings document (every
// setting + its default + a description, as JSONC) and a user settings.json that
// overrides it — both openable from the command palette, like VSCode's
// "Preferences: Open Settings (JSON)" / "Open Default Settings (JSON)".
//
// This module owns the files on disk and the default content; applying the
// settings to the running editor is a separate concern (not all are wired yet).

use std::path::PathBuf;

/// `~/.nova`, created if missing. None if no home dir.
pub fn config_dir() -> Option<PathBuf> {
    let home = std::env::var_os("USERPROFILE").or_else(|| std::env::var_os("HOME"))?;
    let dir = PathBuf::from(home).join(".nova");
    std::fs::create_dir_all(&dir).ok()?;
    Some(dir)
}

/// The default settings document (JSONC): every setting, its default, and a
/// one-line description. Mirrors VSCode's key namespace where it maps to Nova.
pub fn default_settings_jsonc() -> &'static str {
    r#"// Default Settings — Nova's built-in configuration and defaults.
// This file is a reference; override any of these in your user settings
// (Preferences: Open Settings (JSON)). Do not edit this file — changes here are
// not saved.
{
    // --- Editor ---

    // Controls the font size in pixels.
    "editor.fontSize": 14,

    // Controls the line height. Use 0 to compute from the font size.
    "editor.lineHeight": 20,

    // The monospace font family used in the editor.
    "editor.fontFamily": "Consolas",

    // The number of spaces a tab is equal to.
    "editor.tabSize": 4,

    // Insert spaces when pressing Tab.
    "editor.insertSpaces": true,

    // Controls how lines should wrap: "off" or "on".
    "editor.wordWrap": "off",

    // Controls the cursor animation style: "blink" or "solid".
    "editor.cursorBlinking": "blink",

    // Render a vertical line after a certain number of monospace characters.
    // Use 0 to disable.
    "editor.rulers": 0,

    // Highlight the current line.
    "editor.renderLineHighlight": true,

    // Show line numbers in the gutter.
    "editor.lineNumbers": true,

    // --- Files ---

    // Controls auto save of editors: "off" or "afterDelay".
    "files.autoSave": "off",

    // The default end-of-line character: "\n" (LF) or "\r\n" (CRLF).
    "files.eol": "\n",

    // The default character encoding.
    "files.encoding": "utf8",

    // Trim trailing whitespace on save.
    "files.trimTrailingWhitespace": false,

    // --- Workbench / appearance ---

    // The color theme. Install a theme extension to add more.
    "workbench.colorTheme": "Nova Dark",

    // The UI (chrome) font family.
    "workbench.fontFamily": "Segoe UI",

    // Show the activity bar on the left.
    "workbench.activityBar.visible": true,

    // Controls the visibility of the sidebar on startup.
    "workbench.sideBar.visible": true
}
"#
}

/// A fresh user settings.json template.
fn user_settings_template() -> &'static str {
    r#"{
    // Override default settings here. See the Default Settings document
    // (Preferences: Open Default Settings (JSON)) for all available keys.
    "editor.fontSize": 14
}
"#
}

/// Write the default settings to `~/.nova/defaultSettings.jsonc` (overwriting, so
/// it always reflects the current build) and return its path.
pub fn default_settings_path() -> Option<PathBuf> {
    let path = config_dir()?.join("defaultSettings.jsonc");
    std::fs::write(&path, default_settings_jsonc()).ok()?;
    Some(path)
}

/// Path to the user settings file, creating it with a template if absent.
pub fn user_settings_path() -> Option<PathBuf> {
    let path = config_dir()?.join("settings.json");
    if !path.exists() {
        std::fs::write(&path, user_settings_template()).ok()?;
    }
    Some(path)
}
